#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "299ko"
name = "299Ko"
description.en = "Simple, fast & lightweight flat-file CMS"
description.fr = "CMS simple, rapide et léger"

version = "2.0.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "GPL-3.0"
website = "https://299ko.ovh/"
admindoc = "https://docs.299ko.ovh/francais"
code = "https://github.com/299Ko/299ko"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "650M"
ram.build = "150M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/299ko"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/299Ko/299ko/archive/refs/tags/v2.0.0.tar.gz"
    sha256 = "7f71860f2f451cf37782b7bc34e9eee29d27b85c138dda8b65781f3f72768b96"

    autoupdate.strategy = "latest_github_tag"
    autoupdate.upstream = "https://github.com/299Ko/299ko"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "php8.3-gd, php8.3-intl, php8.3-mbstring, php8.3-curl, php8.3-xml"
